### PR TITLE
Update astropy min version to 5.0.4

### PR DESCRIPTION
**Pull request by WilliamJamieson**

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
Python 3.7 CI will need to be removed as astropy 5+ does not support 3.7.

**Comment by mcara** [comment]
> The motivation of this is that we need to pin the min version of astropy to 5.0.4

**Comment by mcara** [comment]
> The motivation of this is that we need to pin the min version of astropy to 5.0.4

Why??? `tweakwcs` should work with older versions, I believe. Who **needs** this?

**Comment by mcara** [comment]
can you rebase this PR, please

**Comment by WilliamJamieson** [comment]
> can you rebase this PR, please

Done

**Pull request merged**
