### PR TITLE
Add Zenodo badge

### PR DESCRIPTION
**Pull request by pllim**
Looks like you have a DOI via release webhook. You should advertise it. cc @rosteen 

p.s. Are you still using Azure Pipelines? Why not Actions?

### CODE REVIEW

**Comment by mcara** [comment]
> Are you still using Azure Pipelines? Why not Actions?

It is to not forget about @jhunkeler contribution to this package

**Comment by pllim** [comment]
I think the setuptools stuff needs updating because your sdist build is failing but that is not related to this PR.

```
from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'
```

**Comment by mcara** [comment]
> I think the setuptools stuff needs updating because your sdist build is failing but that is not related to this PR.
> 
> ```
> from setuptools import setup, find_packages
> ModuleNotFoundError: No module named 'setuptools'
> ```

Probably will be solved by https://github.com/spacetelescope/tweakwcs/pull/188 which was awaiting a new `gwcs` release (which, I heard, happened today). So, just patience, please. I am looking into possible modifications to that PR.

**Comment by mcara** [comment]
`setuptools` issue is strange as no other PR was merged since https://github.com/spacetelescope/tweakwcs/commit/c98e703263872ff80dbbfd7aeff16983e2f4d282 and then tests were passing.

**Comment by pllim** [comment]
Python has changed stuff too, so maybe your code just have to modernize the packaging.

**Review by mcara — APPROVED** [review]

**Comment by pllim** [comment]
This is just a PR to add badge, I don't think CI is even needed, so I just merged it. Thanks for the review!

**Pull request merged**
